### ISSUE TITLE
Gem install error

### ISSUE THREAD

**Issue by jedfoster** [at-import/Sassy-Strings#7]
Has this gem been pushed to rubygems.org?

Tried installing it:

```
$ gem install SassyStrings
ERROR:  Could not find a valid gem 'SassyStrings' (>= 0) in any repository
ERROR:  Possible alternatives: sassy-strings
```

And [sassy-strings](http://rubygems.org/gems/sassy-strings) is @Snugug's old version from August 2013, not the @Team-Sass version.

**Comment by KittyGiraudel** [comment]
To clarify things up, the `sassy-strings` gem is an _old_ project from @Snugug made in Ruby (not Sass). I updated the sources with a Sass version of it, new functions, some different stuff and such but it turned out being quite slow (at least much slower than a Ruby version) so we didn't update the gem.

We should probably revert the repository to what it was before.

**Comment by jedfoster** [comment]
Ahh. Makes sense. I had a request to add it to SassMeister.com, https://github.com/jedfoster/SassMeister/issues/64#issuecomment-35177493, which is why I was trying to install it.

No worries. Thanks!
